# Generated by Django 5.1.4 on 2025-02-03 21:26
"""
Module for 1 migration 
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    2 migration
    """
    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
