# Generated by Django 5.1.4 on 2025-02-04 09:49
"""
Module for 3 migration 
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    3 migration
    """
    dependencies = [
        ('payment', '0002_alter_shippingaddress_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='shipping_address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='shipping_full_name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
    ]
