# Generated by Django 5.1.4 on 2025-02-05 20:34
"""
Module for 1 migration 
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    5 migration
    """
    dependencies = [
        ('payment', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
