# Generated by Django 5.1.4 on 2025-01-02 12:19
"""
Module for 2 migration 
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    second migration
    """
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                ),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[
                    ('Pending', 'Pending'),
                    ('Out for delivery', 'Out for delivery'),
                    ('Delivered', 'Delivered')],
                    max_length=200, null=True)
                ),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')
                                           ),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('descreption', models.CharField(max_length=200, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
