# Generated by Django 5.1.4 on 2025-01-02 12:39
"""
Module for 4 migration 
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Fourth migration
    """
    dependencies = [
        ('accounts', '0003_rename_product_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='accounts.book'
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='accounts.customer'
            ),
        ),
    ]
