# Generated by Django 5.1.4 on 2025-01-02 12:44
"""
Module for 5 migration 
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Fifth migration
    """
    dependencies = [
        ('accounts', '0004_order_book_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                ),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
