# Generated by Django 5.1.4 on 2025-01-02 12:48
"""
Module for 6 migration 
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Sixth migration
    """
    dependencies = [
        ('accounts', '0005_tag_order_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
