# Generated by Django 5.1.4 on 2025-01-03 16:00
"""
Module for 8 migration 
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Eighth migration
    """
    dependencies = [
        ('accounts', '0007_remove_customer_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/books/'),
        ),
    ]
