# Generated by Django 5.1.4 on 2025-01-03 17:11
"""
Module for 9 migration 
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Ninth migration
    """
    dependencies = [
        ('accounts', '0008_rename_name_book_title_book_author_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
