# Generated by Django 5.1.4 on 2025-01-03 17:58
"""
Module for 10 migration 
"""
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Tenth migration
    """
    dependencies = [
        ('accounts', '0009_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
