# Generated by Django 5.1.4 on 2025-01-03 18:46
"""
Module for 11 migration 
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Eleventh migration
    """
    dependencies = [
        ('accounts', '0010_book_cover_book_pages_book_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
