# Generated by Django 5.1.4 on 2025-01-18 10:37
"""
Module for 12 migration 
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Twelth migration
    """
    dependencies = [
        ('accounts', '0011_alter_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
