# Generated by Django 5.1.4 on 2025-01-25 17:06
"""
Module for 18 migration 
"""
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Eighteenth migration
    """
    dependencies = [
        ('accounts', '0017_alter_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                ),
                ('content', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField()),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviews',
                    to='accounts.book')
                ),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviews',
                    to=settings.AUTH_USER_MODEL)
                ),
            ],
        ),
    ]
