# Generated by Django 5.1.4 on 2025-01-28 19:53
"""
Module for 20 migration 
"""
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    """
    Twentieth migration
    """
    dependencies = [
        ('accounts', '0019_alter_productreviews_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreviews',
            unique_together={('user', 'book')},
        ),
    ]
