# Generated by Django 5.1.4 on 2025-01-28 19:55
"""
Module for 21 migration 
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Twenty-first migration
    """
    dependencies = [
        ('accounts', '0020_alter_productreviews_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreviews',
            unique_together=set(),
        ),
    ]
