# Generated by Django 5.1.4 on 2025-02-06 10:56
"""
Module for 23 migration 
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Twenty-third migration
    """
    dependencies = [
        ('accounts', '0022_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
