# Generated by Django 5.1.4 on 2025-02-06 10:58
"""
Module for 24 migration 
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Twenty-fourth migration
    """
    dependencies = [
        ('accounts', '0023_profile_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='old_cart',
        ),
    ]
