# Generated by Django 5.1.4 on 2025-02-06 13:10
"""
Module for 25 migration 
"""
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    """
    Twenty-fifth migration
    """
    dependencies = [
        ('accounts', '0024_remove_profile_old_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreviews',
            unique_together={('book', 'user')},
        ),
    ]
